name: "Create Milestone JS"
description: "Creating a milestone or returning an existing one. Pure JS action."
branding:
  icon: "check-circle"
  color: "green"
inputs:
  token:
    description: "GitHub Token."
    required: true
  title:
    description: "The title of a milestone."
    required: true
  state:
    description: "The state of a milestone. Either `open` or `closed`. Default: `open`"
    required: false
    default: "open"
  description:
    description: "The description of a milestone."
    required: false
  due_on:
    description: "The due date of a milestone. Timestamp in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`."
    required: false
outputs:
  id:
    description: "An ID of the created milestone."
  number:
    description: "A Number of the created milestone."
  state:
    description: "A State of the created milestone."
  title:
    description: "A Title of the changed milestone."
  description:
    description: "A Description of the changed milestone."
  due_on:
    description: "The due date of the changed milestone."
runs:
  using: node24
  main: "dist/index.js"
