name: "Test Action"

on:
  pull_request:

concurrency:
  group: ${{ format('{0}-{1}', github.workflow, github.head_ref) }}
  cancel-in-progress: true

jobs:
  create_milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: create
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.run_number }}
      - run: echo "The Number - ${{ steps.create.outputs.number }}"
      - run: echo "The ID - ${{ steps.create.outputs.id }}"
      - run: echo "The State - ${{ steps.create.outputs.state }}"
