name: "Test Action"

on:
  pull_request:

jobs:
  create_milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: create
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Next
      - run: echo "The number ${{ steps.create.outputs.number }}"
